### ISSUE TITLE
🔴 Feature request: Support for search result pages and search result pages within specific channels

### ISSUE THREAD

**Issue by Thomas-Harrell** [sapondanaisriwan/youtube-row-fixer#10]
- Search result pages

[https://www.youtube.com/results?search_query=mkbhd](https://www.youtube.com/results?search_query=mkbhd)

- Search result pages within specific channels

[https://www.youtube.com/@mkbhd/search?query=apple](https://www.youtube.com/@mkbhd/search?query=apple)

- Just like what the following script accomplishes.

[https://greasyfork.org/en/scripts/481422-youtube-search-results-in-grid-view](https://greasyfork.org/en/scripts/481422-youtube-search-results-in-grid-view)

![0JPmiMT](https://github.com/sapondanaisriwan/youtube-row-fixer/assets/106761803/8e9545bf-0456-4f36-aa18-f5bc99e40b80)

**Comment by sapondanaisriwan** [comment]
I have already done that in my old project.
https://github.com/sapondanaisriwan/AdashimaaTube
![image](https://github.com/sapondanaisriwan/youtube-row-fixer/assets/64634605/0b66f3e4-7e34-4a6e-9316-e04f883f0047)
