### ISSUE TITLE
[Feature Request] Dynamic Videos Per Row Based On Resolution

### ISSUE THREAD

**Issue by MarshallWolfie** [sapondanaisriwan/youtube-row-fixer#12]
I have 2 monitors. A 1440p 27" monitor and a 600p 7" monitor. I usually open Youtube on my second smaller monitor while doing something else. Because the screen is very small, the usual setting of 5 videos per row (my preferred choice on my main monitor) makes everything look weird. If I zoom in on the Youtube page, the thumbnails are visible enough but the titles of the videos don't have enough space to show, usually only half of the titles are shown. If I zoom out, the thumbnails are too small while more of the titles are shown but they're too hard too read because the letters are too small. I already install another extension, [Zoom](https://chromewebstore.google.com/detail/zoom-for-google-chrome/lajondecmobodlejlcjllhojikagldgd), which automatically adjusts the zoom level based on the resolution of the monitor. It works well, but it only solves half of the problem. With this extension, the Youtube page zoom level is set at 75% for my second monitor. The thumbnails are visible enough, and most of the titles are shown, but both are still a bit too small. Changing the number of videos per row down from 5 to 4 gives the perfect result, but due to the lack of such feature, it has to be done manually everytime I bring the Youtube window/tab to either one of my 2 monitors.

I hope this could be added in the future. It would be truly helpful for multi-monitor setups like mine.

**Comment by sapondanaisriwan** [comment]
I'm going to add this feature in the next upcoming update.

![19-04-24_22-00](https://github.com/sapondanaisriwan/youtube-row-fixer/assets/64634605/980c246c-9def-4ddc-a312-f13a5f500c37)

![a1o98KcnlB](https://github.com/sapondanaisriwan/youtube-row-fixer/assets/64634605/007e3d95-6447-4b16-9b10-4e0025f5dd1e)

**Comment by MarshallWolfie** [comment]
> I'm going to add this feature in the next upcoming update.
> 
> ![19-04-24_22-00](https://private-user-images.githubusercontent.com/64634605/324004704-980c246c-9def-4ddc-a312-f13a5f500c37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NzQ4MjgsIm5iZiI6MTcxMzU3NDUyOCwicGF0aCI6Ii82NDYzNDYwNS8zMjQwMDQ3MDQtOTgwYzI0NmMtOWRlZi00ZGRjLWEzMTItZjEzYTVmNTAwYzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDAwNTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MWM4NGYxYjdiOGNlOWRmMTNkYmMxOWQzMDUyZWIzNTc5ODJiMjdkNjY0NjIwNTE5NjlhZjEyMWUxMWMxOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ley8-dv6pCbZPvU7Xtg4VSnXxyxt86hPib0N7a4gyTM)
> 
> ![a1o98KcnlB](https://private-user-images.githubusercontent.com/64634605/324004919-007e3d95-6447-4b16-9b10-4e0025f5dd1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NzQ4MjgsIm5iZiI6MTcxMzU3NDUyOCwicGF0aCI6Ii82NDYzNDYwNS8zMjQwMDQ5MTktMDA3ZTNkOTUtNjQ0Ny00YjE2LTliMTAtNGUwMDI1ZjVkZDFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDAwNTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViODI3ODczMTViYjIyNzk2NDUxMGJjOTE0M2M2NTJlZjVmMjU1NDMxNzBjMGE4ZTZhNThiYzhiMzAwNjQ4OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X4qMixaZe4M-lePdZ6QK9lzQIZmK_vAkql5HX6hh4oU)

**Comment by sapondanaisriwan** [comment]
This feature was added in the new version v1.0.5
