### ISSUE TITLE
[Feature request]: Search page

### ISSUE THREAD

**Issue by Bhaalspawn** [sapondanaisriwan/youtube-row-fixer#15]
### Describe the change you'd like

Hello, can you make this extension to work also for search page?
i prefer the tile view (the default view for home and subscriptions) also for search page

PS:i'm using your script for stylus and i'm sad you are not supporting it anymore, could you at least fix the bugs?

**Comment by sapondanaisriwan** [comment]
Can you describe what the bug is? Where it happened?

for me the script is still working for me
![image](https://github.com/sapondanaisriwan/youtube-row-fixer/assets/64634605/730cdfe8-b7e4-48ca-989c-afa1ef015bb6)

**Comment by Bhaalspawn** [comment]
Can i say it here? Ok
There are few things
1) Search page. the only thing i get is the grid view but "no limit width" is doing nothing (as same as the other 3 that i don't use)
![sea](https://github.com/sapondanaisriwan/youtube-row-fixer/assets/20135076/9b2396be-40af-43c4-af8e-145fc25aa100)

2) in the "playlist" tab i see no images for the playlist i save. i tried to disable everything but it didn't work. i have to disable the script to make the images come back

**Comment by sapondanaisriwan** [comment]
For me in the playlist tab I can still see the images. Can you screenshot all you setting?
![11-05-24_22-37](https://github.com/sapondanaisriwan/youtube-row-fixer/assets/64634605/3bab5c83-cfbe-484e-924f-e32aa8b878d0)

**Comment by Bhaalspawn** [comment]
there is not much to show. even if i disable everything i don't see images

can i send you a log instead? you can see if i have a corrupt version. or i could try to reinstall but i don't remember how to do it

**Comment by sapondanaisriwan** [comment]
`139.5 unknown error` is not the bug.
I can't reproduce the missing thumbnail on playlist tab, anyway I'm going to fix the "no limit width" in upcoming update.
