### ISSUE TITLE
[Bug]: AdashimaaTube Bug

### ISSUE THREAD

**Issue by Bhaalspawn** [sapondanaisriwan/youtube-row-fixer#16]
### Describe the bug

it's suddenly showing 1 less video per row than intended in Subscriptions tab on both Vivaldi and Firefox. It wouldn't be a problem if could just set a higher number but it's leaving a blank space instead of the 5th (let's say last) video.

The only way to solve it is to disable "Video appearance" but if i do that, other settings don't work

i understand it's now not developed anymore but can i suggest to leave open the other forum just for these bugs reports? i understand it's now not developed anymore but 

### Screenshots

![Immagine](https://github.com/user-attachments/assets/ad4015cf-2ca4-4135-af91-9084b43576da)

_No response_

**Comment by sapondanaisriwan** [comment]
AdashimaaTube is dead 💀
