### ISSUE TITLE
Thumbnail size and empty space

### ISSUE THREAD

**Issue by asisix** [sapondanaisriwan/youtube-row-fixer#5]
Hi. Sometimes when I refresh the page, the video thumbnails change size and fill the page and because of it an empty space appears. I prefer the option when the covers are a little smaller, can you add this option? https://imgur.com/a/S38JwGF

**Comment by sapondanaisriwan** [comment]
Did you install something like shorts block? The blank spaces appear when shorts got removed.

**Comment by asisix** [comment]
Yes, I had such an extension installed, after deleting everything was fixed. Thank you. I wonder if it is possible to reduce the  thumbnails size and indentation?
