### ISSUE TITLE
stopped working today

### ISSUE THREAD

**Issue by hajj3** [sapondanaisriwan/youtube-row-fixer#8]
this stopped working today, please fix this.

**Comment by salasNicholas** [comment]
it's likely that YT in their perpetual fight with ad blockers fucked up something that broke this extension too

**Comment by salasNicholas** [comment]
if you have ublock origin you can put this 2 lines in your custum filters to get a similar effect to the extension:

youtube.com##ytd-rich-grid-row, #contents.ytd-rich-grid-row:style(display:contents !important;) 
youtube.com##ytd-rich-grid-renderer:style(--ytd-rich-grid-items-per-row: 6 !important;)

(change the 6 in to the number of video you want to see in a row)

**Comment by hajj3** [comment]
if i change the number to 5 which is what i want it doesn't fill the 2nd row as shown in the attached screenshot.

I want to be able to change the number shorts to 6 from 5 too.

It looks like youtube has reduced the number of shorts being shown in the subscriptions page. It used to shown them every few rows now it only has some a few rows from the top. Maybe this is why your extension stopped working.
On 29/11/2023 18:43:28, salasNicholas ***@***.***> wrote:
if you have ublock origin you can put this 2 lines in your custum filters to get a similar effect to the extension:
youtube.com##ytd-rich-grid-row, #contents.ytd-rich-grid-row:style(display:contents !important;)
youtube.com##ytd-rich-grid-renderer:style(--ytd-rich-grid-items-per-row: 6 !important;)
(change the 6 in to the number of video you want to see in a row)

**Comment by hajj3** [comment]
![youtube](https://github.com/sapondanaisriwan/youtube-row-fixer/assets/1085062/e332a6db-bd4b-490f-acf3-b1fa4292bca2)

**Comment by hajj3** [comment]
p.s if it is possible to automatically expand the "show more" button for the shorts that are displayed and give us an option in your extension to do that then that would be great.

**Comment by sapondanaisriwan** [comment]
Fixed :)
