### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by hajj3** [sapondanaisriwan/youtube-row-fixer#9]
when on the main youtube.com page if you scroll down for a while these is a section called "Latest YouTube posts". This section uses the same number of posts per row as the number of videos per row that you select in your extension. I use 5 videos per row but this results in very little text shown next to the video for the posts in the "latest youtube posts" section. I would like for there to be an additional setting in your extension to specify the number of posts to show per row.

Here is a screenshot showing this: https://i.imgur.com/9rnhFya.jpeg

I would also like a setting to expand the "show more" button that shows additional videos or posts by default.

**Comment by sapondanaisriwan** [comment]
I believe the new feature "Post per row" should fix for Latest YouTube posts" section.
![ZRfI96z5sB](https://github.com/sapondanaisriwan/youtube-row-fixer/assets/64634605/fd560f09-6736-4e22-8746-e67e1ea33ee5)
